spring.application.name=user-json-service
spring.datasource.url=jdbc:mysql://localhost:3306/soa_lab
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
server.port=8081